---
processors:
  - stylelint-processor-styled-components

extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-styled-components

syntax: scss

rules:
  selector-pseudo-element-colon-notation: single
  value-list-max-empty-lines: null
  no-duplicate-selectors: null
  rule-empty-line-before: null
  block-no-empty: null
  declaration-empty-line-before: null
  declaration-colon-newline-after: null
  string-quotes: single